#!/usr/bin/python
# -*- coding: utf-8 -*-

DOCUMENTATION = '''


---
module: oracle_ovm_module
short_description: Manage Virtual Storage for VM:s in Oracle Virtual Manager 3.3
description:
    - Best way to use this module in task playbooks is to delegate_to: 127.0.0.1
version_added: "0.0.1"
options:
    ovmHostname:
        description:
            - Hostname/Ipadress to OVM host
        required: true
    ovmPort
        description:
            - Port that OVM listen on
        required: true    
    user
        description:
            - Username for logon to the OVM Web Gui
        required: true
    password
        description:
            - Hostname/Ipadress to OVM host
        required: true
    state
        description:
            - The intended state of the Oracle Cloud Instance
                - present = Create New Cloud Service
                - absent = Delete Existen Cloud Service
                - start = Start Existen Cloud Service VM
                - stop  = Stop Existen Cloud Service VM
                - restart = Restart Existen Cloud Service VM
                - scale = Scale Up or Down Cloud Service VM
        required: true
        choices=["present","absent","start", "stop", "restart","scale"]
    repositoryName
        description:
            - Virtdisk storage repository
        required: false    
    virtualDiskName
        description:
            - Name for virtualdisk
        required: False    
    virtualDiskSize
        description:
            - Size of the disk in bytes. If this is a sparse image, this number does not reflect the actual size of the image on disk, but rather the maximum size of the file. For a non-sparse image this is the same as the size of the file on disk.
        required: False    
    virtualSparse
        description:
            - parse Allocation or Non-sparse Allocation. Sparse Allocation creates a sparse disk, so the size of the disk is initially small and increases as it is used. Sparse allocation is faster than using Non-Sparse Allocation when creating a virtual machine. Non-Sparse Allocation creates the entire disk when the virtual machine is created, and so is slower than creating a sparse disk
        required: False    
    vmName
        description:
            - Name for the Vm
        required: true    
    vmDiskMappingSlott
        description:
            - Fix Disk slott in the vm
        required: true    
        
'''

EXAMPLES = '''

# Create Virtual Disk
oracle_ovm_storage: ovmHostname: 192.168.1.100 ovmPort: 7002 user: admin password: Welcome1 state: present virtualDiskName: KallEDisk repositoryName: ssd_1000 virtualDiskSize: 2 virtualSparse: False

# Remove Virtual Disk from a repository
oracle_ovm_storage: ovmHostname: 192.168.1.100 ovmPort: 7002 user: admin password: Welcome1 state: absent vmName: db1 virtualDiskName: db1_u01 repositoryName: ssd_1000

# Add mapping between VM and Virtualdisk 
oracle_ovm_storage: ovmHostname: 192.168.1.100 ovmPort: 7002 user: admin password: Welcome1 state: mappDisk vmName: db1 description: "dddddd" virtualDiskName: db1_u01 vmDiskMappingSlott: 6

# Remove mapping between vm and disk
oracle_ovm_storage: ovmHostname: 192.168.1.100 ovmPort: 7002 user: admin password: Welcome1 state: removeMappDisk vmName: db1 virtualDiskName: db1_u01 repositoryName: ssd_1000

'''
try:
    import requests
    requests.packages.urllib3.disable_warnings()
    import time
    import json
except ImportError:
    requests_exists = False
else:
    requests_exists = True
"""Return jobStatus of job send to Oracle Cloud
"""

def getVmInfoById(module,VmId, restSession):
    url = 'https://{hostName}:{portNr}/ovm/core/wsapi/rest/Vm/{vmId}'.format(vmId=VmId, hostName=module.params["ovmHostname"],portNr=module.params["ovmPort"])
    vmInfo = restSession.get(url)
    vmInfoJson = json.loads(vmInfo.text)
    return vmInfoJson
    
def getVmInfoByName(module, restSession):
    url = 'https://{hostName}:{portNr}/ovm/core/wsapi/rest/Vm/id'.format(hostName=module.params["ovmHostname"],portNr=module.params["ovmPort"])
    vmResults = restSession.get(url)
    
    for obj in vmResults.json():
    	if 'name' in obj.keys():
            if obj['name']==module.params['vmName']:
                return obj

def waitForJob(joburi,restSession, module):
        while True:
            time.sleep(1)
            r=restSession.get(joburi)
            job=r.json()
            if job['summaryDone']:
                print '{name}: {runState}'.format(name=job['name'], runState=job['jobRunState'])
                if job['jobRunState'].upper() == 'FAILURE':
                    raise Exception('Job failed: {error}'.format(error=job['error']))
                elif job['jobRunState'].upper() == 'SUCCESS':
                    if 'resultId' in job:
                        return job['resultId']
                    break
                else:
                    break

def getJobInfo(restSession, jobID, module):
    url = 'https://{hostName}:{portNr}/ovm/core/wsapi/rest/Job/{jobId}'.format(jobId=jobID,hostName=module.params["ovmHostname"],portNr=module.params["ovmPort"])
    
    resultJobInfo = restSession.get(url)
    return json.loads(resultJobInfo.text)                    
    
def getIdFromName(restSession ,module,resource,obj_name):
        baseUri = 'https://{hostName}:{portNr}/ovm/core/wsapi/rest'.format(hostName=module.params["ovmHostname"],portNr=module.params["ovmPort"])
        uri=baseUri+'/'+resource+'/id'
        r=restSession.get(uri)
        for obj in r.json():
           if 'name' in obj.keys():
            if obj['name']==obj_name:
                return obj
        raise Exception('Failed to find id for {name}'.format(name=obj_name))

def getVirtualDiskByIdInfo(restSession, module, virtualDiskId):
    url = 'https://{hostName}:{portNr}/ovm/core/wsapi/rest/VirtualDisk/{VirtualDiskId}'.format(VirtualDiskId=virtualDiskId, hostName=module.params["ovmHostname"],portNr=module.params["ovmPort"])
    
    virtualDiskResult = restSession.get(url)
    virtualDiskJson = json.loads(virtualDiskResult.text)
    
    return virtualDiskJson

def getVmDiskMappingFromVm(module, restSession):

    vmInfo = getVmInfoById(module,getVmInfoByName(module, restSession)['value'], restSession)
    url = 'https://{hostName}:{portNr}/ovm/core/wsapi/rest/Vm/{vmId}/VmDiskMapping'.format(hostName=module.params["ovmHostname"],portNr=module.params["ovmPort"],vmId=vmInfo['id']['value'])
    vmDiskMappingResult = restSession.get(url)
    
    for obj in vmDiskMappingResult.json():
    	if 'virtualDiskId' in obj.keys():
            if obj['virtualDiskId']['name']==module.params['virtualDiskName']:
                return obj

def virtualDiskExists(module, restSession):
    url = 'https://{hostName}:{portNr}/ovm/core/wsapi/rest/VirtualDisk/id'.format(hostName=module.params["ovmHostname"],portNr=module.params["ovmPort"])
    vmResults = restSession.get(url)
    
    for obj in vmResults.json():
    	if 'name' in obj.keys():
            if obj['name']==module.params['virtualDiskName']:
                return True

    return False
    
def virtualDiskInRepositoryExists(module, restSession):
    repositoryID = getIdFromName(restSession ,module,'Repository',module.params["repositoryName"])
    url = 'https://{hostName}:{portNr}/ovm/core/wsapi/rest/Repository/{repositoryId}/VirtualDisk'.format(hostName=module.params["ovmHostname"],portNr=module.params["ovmPort"],repositoryId=repositoryID['value'])
    vmResults = restSession.get(url)
    
    for obj in vmResults.json():
    	if 'id' in obj.keys():
            if obj['id']['name']==module.params['virtualDiskName']:
                return True

    return False    
 
def virtualDiskHaveMappings(module, restSession):
    virtualDiskInfo = getVirtualDiskByIdInfo(restSession, module, getIdFromName(restSession ,module,'VirtualDisk',module.params["virtualDiskName"])['value'])
    virtualDiskMappings = virtualDiskInfo['vmDiskMappingIds']
    
    if len(virtualDiskMappings) >=1:
        return True
    else:
        return False
    
    
def vmDiskMappingExists(module, restSession):

    vmInfo = getVmInfoById(module,getVmInfoByName(module, restSession)['value'], restSession)
    url = 'https://{hostName}:{portNr}/ovm/core/wsapi/rest/Vm/{vmId}/VmDiskMapping'.format(hostName=module.params["ovmHostname"],portNr=module.params["ovmPort"],vmId=vmInfo['id']['value'])
    vmResults = restSession.get(url)
    
    for obj in vmResults.json():
    	if 'virtualDiskId' in obj.keys():
            if obj['virtualDiskId']['name']==module.params['virtualDiskName']:
                return True

    return False      

def repositoryExists(module, restSession):
    url = 'https://{hostName}:{portNr}/ovm/core/wsapi/rest/Repository/id'.format(hostName=module.params["ovmHostname"],portNr=module.params["ovmPort"])
    vmResults = restSession.get(url)
    
    for obj in vmResults.json():
    	if 'name' in obj.keys():
            if obj['name']==module.params['repositoryName']:
                return True

    return False

def createVirtualDisk(module, restSession):

    if not virtualDiskExists(module, restSession):
        repositoryID = getIdFromName(restSession ,module,'Repository',module.params['repositoryName'])
        url = 'https://{hostName}:{portNr}/ovm/core/wsapi/rest/Repository/{repositoryId}/VirtualDisk'.format(hostName=module.params["ovmHostname"],portNr=module.params["ovmPort"],repositoryId=repositoryID['value'])
    
        
        data = {"diskType" : "VIRTUAL_DISK",
                "name": module.params['virtualDiskName'],
                "size": module.params['virtualDiskSize'] * 1024 * 1024 * 1024,
                }
        createVirtualDiskResult = restSession.post(url, data=json.dumps(data),params={"sparse": module.params['virtualSparse']} )
        createVirtualDiskJson = json.loads(createVirtualDiskResult.text)
        
        jobId = createVirtualDiskJson['id']['value']
        waitModifyJob = waitForJob(createVirtualDiskJson['id']['uri'],restSession, module)
        
        jobInfo = getJobInfo(restSession, jobId, module)
        
        return jobInfo['resultId']['value']
    else:
        module.exit_json(msg='vmDisk Exists', changed=False)
    
def createVmDiskMapping(module, restSession):
    if not vmDiskMappingExists(module, restSession):
        virtualDiskInfo = getVirtualDiskByIdInfo(restSession, module, getIdFromName(restSession ,module,'VirtualDisk',module.params["virtualDiskName"])['value'])
        vmInfo = getVmInfoById(module,getVmInfoByName(module, restSession)['value'], restSession)
        
        url = 'https://{hostName}:{portNr}/ovm/core/wsapi/rest/Vm/{vmId}/VmDiskMapping'.format(hostName=module.params["ovmHostname"],portNr=module.params["ovmPort"],vmId=vmInfo['id']['value'])
        
        data = {"id":{"type":"com.oracle.ovm.mgr.ws.model.VmDiskMapping"},
                        "virtualDiskId" :{
                                            "type":"com.oracle.ovm.mgr.ws.model.VirtualDisk",
                                            "value" : virtualDiskInfo['id']['value']
                                         },
                        "diskTarget" : module.params["vmDiskMappingSlott"],
                        "name" : module.params["virtualDiskName"],
                        "description" : module.params["description"],
                    }
        createVmdDiskMappingResult = restSession.post(url, data=json.dumps(data))
        createVmdDiskMappingJson = json.loads(createVmdDiskMappingResult.text)
        waitModifyJob = waitForJob(createVmdDiskMappingJson['id']['uri'],restSession, module)
    else:
         module.exit_json(msg='mapping Exists', changed=False)

def delVmDiskMapping(restSession, module, vmDiskMappingId):
    vmInfo = getVmInfoById(module,getVmInfoByName(module, restSession)['value'], restSession)
    url = 'https://{hostName}:{portNr}/ovm/core/wsapi/rest/Vm/{VmId}/VmDiskMapping/{VmDiskMappingId}'.format(VmId=vmInfo['id']['value'], VmDiskMappingId=vmDiskMappingId, hostName=module.params["ovmHostname"],portNr=module.params["ovmPort"])
    
    delVmDiskMappingResult = restSession.delete(url)
    delVmDiskMappingJson = json.loads(delVmDiskMappingResult.text)
    
    waitModifyJob = waitForJob(delVmDiskMappingJson['id']['uri'],restSession, module)

def delVmDiskMappingFromVm(restSession, module):
    vmInfo = getVmInfoById(module,getVmInfoByName(module, restSession)['value'], restSession)
    virtuelDiskMappInfo = getVmDiskMappingFromVm(module, restSession)
    
    if virtualDiskExists(module, restSession):
        if vmDiskMappingExists(module, restSession):
            delVmDiskMapping(restSession, module, virtuelDiskMappInfo['id']['value'])
            module.exit_json(msg='virtualdiskmapping removed', changed=True)
        else:
            module.exit_json(msg='VirtualDisk MApping on Vm not Exists', changed=False)
    else:
        module.exit_json(msg='VirtualDisk not Exists', changed=False)

def delVirtualDisk(restSession, module):
    virtualDiskInfo = getVirtualDiskByIdInfo(restSession, module, getIdFromName(restSession ,module,'VirtualDisk',module.params["virtualDiskName"])['value'])
    url = 'https://{hostName}:{portNr}/ovm/core/wsapi/rest/Repository/{repositoryId}/VirtualDisk/{virtualDiskId}'.format(repositoryId=virtualDiskInfo['repositoryId']['value'], virtualDiskId=virtualDiskInfo['id']['value'], hostName=module.params["ovmHostname"],portNr=module.params["ovmPort"])
    delVirtualDiskResult = restSession.delete(url)
    delVirtualDiskJson = json.loads(delVirtualDiskResult.text)
    
    waitModifyJob = waitForJob(delVirtualDiskJson['id']['uri'],restSession, module)

def delVirtualDiskInRepository(restSession, module):
    
    if virtualDiskInRepositoryExists(module, restSession):
        if not virtualDiskHaveMappings(module, restSession):
            delVirtualDisk(restSession, module)
            module.exit_json(msg='VirtualDisk in Repo removed', changed=True)
        else:
            module.exit_json(msg='VirtualDisk in Repo Still Have Mapping', changed=False)
    else:
        module.exit_json(msg='VirtualDisk in Repo not exists', changed=False)
    
def main():
    msg = ['']
    module = AnsibleModule(
        argument_spec = dict(
            ovmHostname		        = dict(required=True),
            ovmPort					= dict(required=True),
            user                    = dict(required=True),
            password                = dict(required=True),
            state                   = dict(choices=["present","absent","mappDisk","removeMappDisk"]),
            repositoryName          = dict(required=False),
            description             = dict(required=False),
            virtualDiskName         = dict(required=False),
            virtualDiskSize         = dict(required=False),
            virtualSparse		    = dict(required=False),
            vmName		            = dict(required=False),
            vmDiskMappingSlott      = dict(required=False),
        ),
        supports_check_mode=False
    )
    
    restSession = requests.Session()
    restSession.auth = (module.params["user"], module.params["password"])
    restSession.headers.update({'Accept': 'application/json', 'Content-Type': 'application/json'})
    restSession.verify=False
    if module.params["state"] == "mappDisk":
        createVmDiskMapping(module, restSession)
        module.exit_json(msg='vmDisk Created', changed=True)
    if module.params["state"] == "present":
        createVirtualDisk(module, restSession)
        module.exit_json(msg='vmDisk Created', changed=True)
    elif module.params["state"] == "removeMappDisk":
        delVmDiskMappingFromVm(restSession, module)
    elif module.params["state"] == "absent":
        delVirtualDiskInRepository(restSession, module)
    else:
        module.fail_json(msg="Wrong state")
    

   

from ansible.module_utils.basic import *
if __name__ == '__main__':
    main()